logging:
#  config: log4j2.yml
  level:
    org:
      hibernate:
        type: info
spring:
  profiles:
    active: production
  main:
    banner-mode: off
  jackson:
    serialization:
      INDENT_OUTPUT: true
  jpa:
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  datasource:
    hikari:
      maximum-pool-size: 10

    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/testJpa
    username: root
    password: whwndgndl2

    #database=h2
    #spring.datasource.schema=classpath*:db/${database}/schema.sql
    #spring.datasource.data=classpath*:db/${database}/data.sql
    #spring.datasource.initialization-mode=always
  devtools:
    livereload:
      enabled: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 3500MB
      max-request-size: 3500MB
  mvc:
    favicon:

  rexources:
    cache:
      period:0

